/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable

export const indexTemplateHtml = `<span [title]="title" (mouseenter)="mouseenter()" (mouseleave)="mouseleave()">{{timeText}}</span>`
// tslint:enable
