// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, openBlock as _openBlock, toDisplayString as _toDisplayString } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("span", {
    title: _ctx.title,
    onMouseenter: _cache[1] || (_cache[1] = $event => (_ctx.mouseenter())),
    onMouseleave: _cache[2] || (_cache[2] = $event => (_ctx.mouseleave()))
  }, _toDisplayString(_ctx.timeText), 41 /* TEXT, PROPS, HYDRATE_EVENTS */, ["title"]))
}
/* eslint-enable */
// tslint:enable
