// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { RelativeTime } from "./index"

export function indexTemplateHtml(this: RelativeTime) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('span',{attrs:{"title":_vm.title},on:{"mouseenter":function($event){return _vm.mouseenter()},"mouseleave":function($event){return _vm.mouseleave()}}},[_vm._v(_vm._s(_vm.timeText))])}
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
