/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const angularTemplateHtml = `<span [title]="title" (mouseenter)="mouseenter()" (mouseleave)="mouseleave()">{{timeText}}</span>`;
